### ISSUE TITLE
Port for rTorrent

### ISSUE THREAD

**Issue by carbon658** [pierrickrouxel/iocage-plugin-rtorrent-flood#2]
Can you add to the readme which port and logins info rTorrent is using by default for other apps to access? I am attempting to connect Sonarr, Radarr, and other rTorrent applications and cannot get access.

**Comment by xal3xhx** [comment]
any luck on this? im trying to do the same thing

**Comment by carbon658** [comment]
I haven't. I actually gave up on it unfortunately.

**Comment by Bluebie** [comment]
it seems to be connected via a unix domain socket, rather than a network socket, so I don't think rtorrent's API is actually available on the network at all.
