### ISSUE TITLE
Flood-UI/flood is apparently abandoned

### ISSUE THREAD

**Issue by rgrvlsk** [pierrickrouxel/iocage-plugin-rtorrent-flood#5]
Sadly, it seems like [Flood-UI/flood](https://github.com/Flood-UI/flood) might have been abandoned. Its last commit to date was on November 24 2019.

Flood-UI/flood#877 Seems to suggest an active fork by @jesec: [jesec/flood](https://github.com/jesec/flood), las commit being merely hours ago and activity is quite consistent. While still relatively obscure, they seem to have been intensely working in the last few weeks and have included a [great deal of improvements](https://github.com/jesec/flood/blob/master/CHANGELOG.md) to the frontend.

I haven't personally tested this particular fork, and it seems to be in need for additional contributors, but it seems promising.

It might be a fitting replacement to the now stale and feature lacking original project.

**Comment by pierrickrouxel** [comment]
I'm agreed with you, the project original project is abandoned.
I have no time to do the work. If you want to migrate my plugin, feel free to publish a pull request. I'm ok to use this fork..

**Comment by rgrvlsk** [comment]
I'm not skilled nearly enough in FreeNAS (or FreeBSD for that matter) to get into this. In fact I'm just now starting to mess with FreeNAS myself, as a user. I wish I had the time to learn, though. I don't think it's a drop-in replacement and upgrades might be breaking old setups.

Hopefully @jesec themself can help out with that, being that they seem to be pretty active.
